---
# Source: https://electrolama.com/radio-docs/#step-2-download-the-correct-firmware-for-your-stick
- name: Initial setup
  block:
    - name: Creating work directory
      ansible.builtin.file:
        path: "{{ work_dir }}"
        state: directory
      register: create_workdir
          
    - name: Check if ZIP file is not already downloaded at dir
      ansible.builtin.stat:
        path: "{{ work_dir }}/CC2652R_coordinator_20210120.zip"
      register: get_firmware_zipfile

    - name: Check if HEX file is not already extracted at dir
      ansible.builtin.stat:
        path: "{{ work_dir }}/CC2652R_coordinator_20210120.hex"
      register: get_firmware_hexfile

    - name: Check if Python modules are not already downloaded at "{{ work_dir }}"
      ansible.builtin.stat:
        path: "{{ work_dir }}/cc2538-bsl-master"
      register: get_pythonmodules_folder

    - name: Downloading correct firmware for a CC2652R stick
      ansible.builtin.get_url: 
        url: https://github.com/Koenkk/Z-Stack-firmware/raw/master/coordinator/Z-Stack_3.x.0/bin/CC2652R_coordinator_20210120.zip
        dest: "{{ work_dir }}/CC2652R_coordinator_20210120.zip"
      when: 
        - create_workdir.state == 'directory'
        - get_firmware_zipfile.stat.exists == false
    
    - name: Unzip downloaded firmware zip
      ansible.builtin.unarchive:
        src: "{{ work_dir }}/CC2652R_coordinator_20210120.zip"
        dest: "{{ work_dir }}"
      when: 
        - create_workdir.state == 'directory'
        - get_firmware_hexfile.stat.exists == false
      register: unzip_firmware_hexfile

    - name: Downloading python modules
      ansible.builtin.get_url: 
        url: "https://codeload.github.com/JelmerT/cc2538-bsl/zip/master"
        dest: "{{ work_dir }}/cc2538-bsl.zip"
      when: get_pythonmodules_folder.stat.exists == false

    - name: Unzipping Python modules zip file
      ansible.builtin.unarchive:
        src: "{{ work_dir }}/cc2538-bsl.zip"
        dest: "{{ work_dir }}"
      when: get_pythonmodules_folder.stat.exists == false